name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test -B
  deliver-jar:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build the JAR file with Maven
        run: mvn package -B
      - name: Upload the JAR file to GitHub as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: target/*.jar
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: deliver-jar
    steps: 
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-files
          path: ./build
      - name: Create ZIP archive
        run: |
          ls -la ./build
          zip -r build.zip ./build
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          body: "Our first release!"
          draft: false
          prerelease: false
